### ISSUE TITLE
Release on userstyles.org?

### ISSUE THREAD

**Issue by hayleox** [resir014/stars-not-hearts#1]
Instead of requiring manual configuration of the style, you could just put this up on userstyles.org. And that way, you could have one style that covers both Twitter.com and Tweetdeck.

**Comment by resir014** [comment]
@oxguy3 Ah, thanks! I'll look into it later today.

**Comment by resir014** [comment]
And done!

You can find the userstyles.org page [here](https://userstyles.org/styles/121252/stars-not-hearts).
